controller_list:
  - name: /left/left_gen3_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_joint_1
      - left_joint_2
      - left_joint_3
      - left_joint_4
      - left_joint_5
      - left_joint_6
      - left_joint_7
  - name: /right/right_gen3_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - right_joint_1
      - right_joint_2
      - right_joint_3
      - right_joint_4
      - right_joint_5
      - right_joint_6
      - right_joint_7
  - name: /left/left_robotiq_2f_85_gripper_controller
    action_ns: gripper_cmd
    type: GripperCommand
    default: True
    joints:
      - left_finger_joint
  - name: /right/right_robotiq_2f_85_gripper_controller
    action_ns: gripper_cmd
    type: GripperCommand
    default: True
    joints:
      - right_finger_joint